### ISSUE TITLE
Add translation dropdown and apply i18n

### ISSUE THREAD

**Issue by ifirmawan** [akvo/national-wash-mis#19]
## TODO/Done

- [x] Show dropdown translation in header section

### Update ui-text with i18n.js
- [x] header and footer 
- [x] add-organisation
- [x] add-user
- [x] approvals
- [x] approvers-tree
- [x] control-center
- [x] dashboard
- [x] export-data
- [x] forms
- [x] home
- [x] login
- [x] manage-data
- [x] news-events
- [x] organisations
- [x] profile
- [x] questionnaires
- [x] reports
- [x] settings
- [x] submissions
- [x] upload-data
- [x] users

**Comment by joycarpediem** [comment]
@ifirmawan , what is the status on this one and what is the remaining effort that is required ?
